services:
  mysql-db:
    image: mysql:8.0
    container_name: projeto_requisicoes_recursos
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  backend-app:
    image: serversideup/php:8.3-fpm
    container_name: projeto_requisicoes_backend
    restart: always
    tty: true
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/var/www/html
    working_dir: /var/www/html
    depends_on:
      - mysql-db

  frontend-app:
    image: node:20-alpine
    container_name: projeto_requisicoes_frontend
    restart: always
    user: "node"
    working_dir: /home/node/app
    volumes:
      - ./frontend:/home/node/app
    ports:
      - "4200:4200"
    command: sh -c "npm install && npx ng serve --host 0.0.0.0 --poll 2000"
    depends_on:
      - backend-app

volumes:
  mysql_data: